/*
 * pitch_pid.h
 *
 * Portable ANSI C (C89) interface for the pitch-attitude PID controller.
 *
 * This is an INDEPENDENT, hand-written reference implementation of the
 * exact same algorithm as src/control/pid_update.m and the
 * pid_controller_block MATLAB Function block in
 * simulink/build_pitch_control_model.m -- written by hand, not
 * generated by Embedded Coder, because Embedded Coder itself requires a
 * MATLAB/Simulink license that was not available in the sandbox this
 * project was built in (see docs/04_verification_note.md).
 *
 * Its purpose is cross-validation: once you run
 * simulink/configure_embedded_coder.m yourself and Embedded Coder
 * produces its own generated C, sim/main_embedded_crossvalidation.m
 * compares three independent implementations -- plain MATLAB, this
 * hand-written C, and the actual Embedded-Coder-generated C -- against
 * the same test vectors. Two independent implementations already
 * agreeing (MATLAB vs. this file, checked in this repo before you ever
 * run Simulink -- see embedded/README.md) is a stronger validation
 * signal than either one alone.
 *
 * Deliberately explicit-state (no static/global controller state),
 * matching the calling convention of src/control/pid_update.m, so a
 * caller can run multiple independent controller instances (e.g. one
 * per stage, reset at separation) without them interfering.
 */

#ifndef PITCH_PID_H
#define PITCH_PID_H

typedef struct {
    double integral;
    double prev_err;
    int first_call;   /* 1 on the very first call, 0 thereafter */
} PitchPidState;

typedef struct {
    double kp;
    double ki;
    double kd;
    double out_limit;
} PitchPidGains;

/* Zero-initializes state, matching src/control/pid_init.m. */
void pitch_pid_init(PitchPidState *state);

/*
 * One discrete PID step. Returns the saturated controller output and
 * updates *state in place (mirrors the [u, pid_state_out] =
 * pid_update(err, dt, gains, pid_state_in) signature in MATLAB, with
 * the output-state passed by pointer instead of returned by value,
 * which is the natural C/embedded equivalent).
 */
double pitch_pid_update(double err, double dt, const PitchPidGains *gains, PitchPidState *state);

#endif /* PITCH_PID_H */
