function add_project_paths()
% ADD_PROJECT_PATHS  Add every project source folder to the MATLAB/Octave path.
%
%   Call this once at the top of any sim/ or tests/ entry-point script.
%   Resolves paths relative to this file's own location, so it works
%   regardless of the current working directory the script is launched
%   from.

    this_file = mfilename('fullpath');
    src_utilities_dir = fileparts(this_file);
    project_root = fileparts(fileparts(src_utilities_dir)); % .../src/utilities -> project root

    folders = {
        fullfile(project_root, 'config'), ...
        fullfile(project_root, 'src', 'environment'), ...
        fullfile(project_root, 'src', 'dynamics'), ...
        fullfile(project_root, 'src', 'guidance'), ...
        fullfile(project_root, 'src', 'control'), ...
        fullfile(project_root, 'src', 'staging'), ...
        fullfile(project_root, 'src', 'integration'), ...
        fullfile(project_root, 'src', 'telemetry'), ...
        fullfile(project_root, 'src', 'visualization'), ...
        fullfile(project_root, 'src', 'utilities'), ...
        fullfile(project_root, 'simulink'), ...
        fullfile(project_root, 'tests') ...
    };

    for i = 1:length(folders)
        if exist(folders{i}, 'dir')
            addpath(folders{i});
        end
    end

end
