function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "pitch_control_loop"};
	this.sidHashMap["pitch_control_loop"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "pitch_control_loop:5"};
	this.sidHashMap["pitch_control_loop:5"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "pitch_control_loop:2"};
	this.sidHashMap["pitch_control_loop:2"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/Clock"] = {sid: "pitch_control_loop:1"};
	this.sidHashMap["pitch_control_loop:1"] = {rtwname: "<Root>/Clock"};
	this.rtwnameHashMap["<Root>/damping_gain"] = {sid: "pitch_control_loop:6"};
	this.sidHashMap["pitch_control_loop:6"] = {rtwname: "<Root>/damping_gain"};
	this.rtwnameHashMap["<Root>/err_sum"] = {sid: "pitch_control_loop:3"};
	this.sidHashMap["pitch_control_loop:3"] = {rtwname: "<Root>/err_sum"};
	this.rtwnameHashMap["<Root>/inv_inertia_gain"] = {sid: "pitch_control_loop:8"};
	this.sidHashMap["pitch_control_loop:8"] = {rtwname: "<Root>/inv_inertia_gain"};
	this.rtwnameHashMap["<Root>/moment_sum"] = {sid: "pitch_control_loop:7"};
	this.sidHashMap["pitch_control_loop:7"] = {rtwname: "<Root>/moment_sum"};
	this.rtwnameHashMap["<Root>/pid_controller_block"] = {sid: "pitch_control_loop:5"};
	this.sidHashMap["pitch_control_loop:5"] = {rtwname: "<Root>/pid_controller_block"};
	this.rtwnameHashMap["<Root>/pid_input_zoh"] = {sid: "pitch_control_loop:4"};
	this.sidHashMap["pitch_control_loop:4"] = {rtwname: "<Root>/pid_input_zoh"};
	this.rtwnameHashMap["<Root>/pitch_program_block"] = {sid: "pitch_control_loop:2"};
	this.sidHashMap["pitch_control_loop:2"] = {rtwname: "<Root>/pitch_program_block"};
	this.rtwnameHashMap["<Root>/pitch_scope"] = {sid: "pitch_control_loop:11"};
	this.sidHashMap["pitch_control_loop:11"] = {rtwname: "<Root>/pitch_scope"};
	this.rtwnameHashMap["<Root>/theta_dot_integrator"] = {sid: "pitch_control_loop:9"};
	this.sidHashMap["pitch_control_loop:9"] = {rtwname: "<Root>/theta_dot_integrator"};
	this.rtwnameHashMap["<Root>/theta_integrator"] = {sid: "pitch_control_loop:10"};
	this.sidHashMap["pitch_control_loop:10"] = {rtwname: "<Root>/theta_integrator"};
	this.rtwnameHashMap["<Root>/theta_out"] = {sid: "pitch_control_loop:12"};
	this.sidHashMap["pitch_control_loop:12"] = {rtwname: "<Root>/theta_out"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "pitch_control_loop:5:1"};
	this.sidHashMap["pitch_control_loop:5:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S2>:1"] = {sid: "pitch_control_loop:2:1"};
	this.sidHashMap["pitch_control_loop:2:1"] = {rtwname: "<S2>:1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
